CREATE DATABASE IF NOT EXISTS db_library DEFAULT CHARACTER SET utf8mb4;
USE db_library;

DROP TABLE IF EXISTS db_library.tb_borrowed;

CREATE TABLE db_library.tb_borrowed (
idborrow INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
desname VARCHAR(128) NOT NULL,
dtregister TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
dtreturn DATE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

DROP TABLE IF EXISTS db_library.tb_books;

CREATE TABLE db_library.tb_books (
idbook INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
idborrow INT NOT NULL,
destitle VARCHAR(64) NOT NULL,
desauthor VARCHAR(64) NOT NULL,
descategory VARCHAR(64) NOT NULL,
dtregister TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
FOREIGN KEY (idborrow) REFERENCES tb_borrowed (idborrow) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

DROP TABLE IF EXISTS db_library.tb_user;

CREATE TABLE db_library.tb_user (
iduser INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
deslogin VARCHAR (64) NOT NULL,
despassword VARCHAR(256) NOT NULL,
dtregister TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

